#!/usr/bin/perl -s

my $Help = ($h or $help or $H or $HELP);

&print_help if $Help;

my $Keep = ($k or $keep or $K or $KEEP);
my $Gzip = ($g or $gzip or $z);
my $nThread = ($n or 4);

use strict;

my $dir = ($ARGV[0] or 'ionosphere');
chdir $dir or die "Could not cd into $dir/\n";
my @files = glob('*_b1.*');

my $file1;   # _b1 file
my $file2;   # _b2 file
my $fileout; # concatenated file
my $err;     # error message from cat


my @SortedFiles = sort @files;
my $nFiles = $#SortedFiles+1;
if($nThread > 1){
    foreach my $iThread (1..$nThread){
        # parent process does nothing
	next if fork();
        for (my $iFile = $iThread-1; $iFile<$nFiles; $iFile+=$nThread){
            $file1 = $SortedFiles[$iFile];
            &process_file($file1);
        }
        exit;
    }
    foreach (1..$nThread){wait};
}else{
    foreach $file1 (@SortedFiles){&process_file($file1)}
}

if($Gzip){
    @files = sort glob('*.idl');
    $nFiles = $#files+1;
    if($nThread > 1){
	foreach my $iThread (1..$nThread){
	    # parent process does nothing
	    next if fork();
	    for (my $iFile = $iThread-1; $iFile<$nFiles; $iFile+=$nThread){
		$fileout = $files[$iFile];
		$err = `gzip -f $fileout`;
		die "Error occured: $err\n" if $err;
	    }
	    exit;
	}
	foreach (1..$nThread){wait};
    }else{
	foreach $fileout (@files){
	    $err = `gzip -f $fileout`;
	    die "Error occured: $err\n" if $err;
	}
    }
}

exit 0;

sub process_file{
    $file2 = $file1;
    $file2 =~ s/b1/b2/;
    $fileout = $file1;
    $fileout =~ s/_b1//;
    print "cat $file1 $file2 > $fileout\n";
    $err = `cat $file1 $file2 > $fileout`;
    die "Error occured: $err\n" if $err;
    unlink($file1, $file2) unless $Keep;
}

##############################################################################
sub print_help{

    print "
Purpose:
   Concatanate north and south blocks into a single idl file.

Usage:
   pION [-h] [-k] [-g] [-n] [DIR]

   -h -help    - print this help message
   -k -keep    - keep original files
                 Default is to delete the two hemisphere files.
   -g -gzip    - gzip the output files
   -n 	       - Number of processors used (default of 4)
                 Default is to leave the output files uncompressed
   DIR         - name of the directory to process
                 Default is DIR = 'ionosphere'

Examples:

   Process files in the ionosphere/ directory:
pION

   Process files in the iono_new/ directory and keep originals:
pION -k iono_new
  
";
    exit 1;

}
